# Setup
title:        বেতুয়া ক্লাব
tagline:      বেতুয়া ক্লাব রেজিষ্ট্রেশন 
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       betua club
  url:        https://betuaclub.ml

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
