theme: jekyll-theme-cayman
title: বেতুয়া ক্লাব
description: Internet Service updated
markdown: kramdown
kramdown:
   auto_ids: true
---
title-heading: false
---

# This is my custom heading

This is my content.
<script src="http://code.jquery.com/jquery-1.4.2.min.js"></script> <script> var x = document.getElementsByClassName("site-footer-credits"); setTimeout(() => { x[0].remove(); }, 10); </script>
